### ISSUE TITLE
Build failed while trying to build in my ubuntu with Qt 4.8 version

### ISSUE THREAD

**Issue by arunkumaraymuo** [bluetiger9/SmtpClient-for-Qt#23]
Thanks for this great work but build failed in ubunu

I downloaded the zip file and tried to compile the source in Ubuntu with Qt 4. Compilation failed with the following error

(.text+0x18):-1: error: undefined reference to `main'
(.text+0x18):-1: error: undefined reference to`main'
